name: CI

on:
  push:
    branches: [ main, master ]
  pull_request:
    branches: [ main, master ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      # 1️ Descarga el código del repo
      - uses: actions/checkout@v4

      # 2️ Configura Node.js (usa versión 18 y activa caché para pnpm)
      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 18
          cache: 'pnpm'

      # 3️ Habilita pnpm (incluido en Node vía Corepack)
      - name: Enable pnpm
        run: corepack enable

      # 4️ Instala dependencias del proyecto
      - name: Install dependencies
        run: pnpm install

      # 5️ Ejecuta el linter (Next.js)
      - name: Lint
        run: pnpm lint

      # 6️ Compila el proyecto Next.js
      - name: Build
        run: pnpm build

      # 7️ Ejecuta tests (si existen)
      - name: Run tests (if present)
        run: pnpm test || echo "No tests configured"
