name: CI

on:
  push:
    branches: [ main, master ]
  pull_request:
    branches: [ main, master ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      # 1️⃣ Descarga el código
      - uses: actions/checkout@v4

      # 2️⃣ Configura Node.js (sin cache aún)
      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 18

      # 3️⃣ Instala pnpm globalmente
      - name: Install pnpm
        run: |
          npm install -g pnpm
          pnpm --version

      # 4️⃣ Habilita caché manualmente
      - name: Cache pnpm store
        uses: actions/cache@v4
        with:
          path: ~/.pnpm-store
          key: ${{ runner.os }}-pnpm-${{ hashFiles('pnpm-lock.yaml') }}
          restore-keys: |
            ${{ runner.os }}-pnpm-

      # 5️⃣ Instala dependencias
      - name: Install dependencies
        run: pnpm install

      # 6️⃣ Ejecuta lint
      - name: Lint
        run: pnpm lint

      # 7️⃣ Compila el proyecto
      - name: Build
        run: pnpm build

      # 8️⃣ Corre tests (si existen)
      - name: Run tests (if present)
        run: pnpm test || echo "No tests configured"
